baseURL = 'https://datapaganism.github.io/cooking/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true